name: mcr-ts

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - rdkit
  - openbabel
  - pdbfixer
  - openmm
  - smina
  - numpy
  - pandas
  - scipy
  - tqdm
  - pip:
      - datamol
      - meeko
